// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Examination_System.Models;

public partial class Branch
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Location { get; set; }

    public virtual ICollection<Department> Departments { get; set; } = new List<Department>();

    public virtual ICollection<Student> Students { get; set; } = new List<Student>();
}