// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Examination_System.Models;

public partial class Course
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int Duration { get; set; }

    public int Grade { get; set; }

    public virtual ICollection<CourseDepartment> CourseDepartments { get; set; } = new List<CourseDepartment>();

    public virtual ICollection<CourseTopic> CourseTopics { get; set; } = new List<CourseTopic>();

    public virtual ICollection<Question> Questions { get; set; } = new List<Question>();

    public virtual ICollection<Instructor> Insts { get; set; } = new List<Instructor>();

    public virtual ICollection<Student> Students { get; set; } = new List<Student>();
}