// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Examination_System.Models;

public partial class CourseTopic
{
    public int CourseId { get; set; }

    public string Topic { get; set; }

    public virtual Course Course { get; set; }
}