// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Examination_System.Models;

public partial class DeptInst
{
    public int DeptId { get; set; }

    public int InstId { get; set; }

    public DateTime? HiringDate { get; set; }

    public virtual Department Dept { get; set; }

    public virtual Instructor Inst { get; set; }
}