// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Examination_System.Models;

public partial class ExamStQ
{
    public int ExamId { get; set; }

    public int StudentId { get; set; }

    public int QId { get; set; }

    public string Answer { get; set; }

    public virtual Exam Exam { get; set; }

    public virtual Question QIdNavigation { get; set; }

    public virtual Student Student { get; set; }
}