// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Examination_System.Models;

public partial class Exam
{
    public int Id { get; set; }

    public string Title { get; set; }

    public int NumTf { get; set; }

    public int NumMcq { get; set; }

    public virtual ICollection<ExamStQ> ExamStQs { get; set; } = new List<ExamStQ>();
}