// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Examination_System.Models;

public partial class Instructor
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int Salary { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public virtual ICollection<DeptInst> DeptInsts { get; set; } = new List<DeptInst>();

    public virtual ICollection<Course> Courses { get; set; } = new List<Course>();
}