// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Examination_System.Models;

public partial class QuestionChoice
{
    public int QId { get; set; }

    public string Choice { get; set; }

    public bool IsCorrect { get; set; }

    public virtual Question QIdNavigation { get; set; }
}